<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ConnectCommandBPEL"
     targetNamespace="http://xmlns.oracle.com/ConnectCommandApplication/ConnectCommandProject/ConnectCommandBPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/ConnectCommandApplication/ConnectCommandProject/ConnectCommandBPEL"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
    >
    <plnk:partnerLinkType name="ConnectCommandBPEL">
        <plnk:role name="ConnectCommandBPELProvider" portType="client:ConnectCommandBPEL"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/ConnectCommandApplication/ConnectCommandProject/ConnectCommandBPEL"
                 schemaLocation="../Schemas/ConnectCommandBPEL.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ConnectCommandBPELRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="ConnectCommandBPELResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="ConnectCommandBPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:ConnectCommandBPELRequestMessage"/>
            <wsdl:output message="client:ConnectCommandBPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
